#!/usr/bin/env bash
# pull-from-ec2.sh -- run from your LAPTOP. Downloads license files,
# Maven creds, and per-deployment state from a deployed EC2 host
# into a timestamped backup directory before `terraform destroy`.
#
# What gets pulled:
#   ~/graphwise-stack-aws/files/licenses/*           (vendor blobs)
#   ~/.ontotext/maven-user                           (Graphwise Maven login)
#   ~/.ontotext/maven-pass                           (Graphwise Maven password)
#   ~/graphwise-secrets.yaml                         (Terraform-generated n8n
#                                                     encryption key overlay --
#                                                     also recoverable from
#                                                     terraform state, but
#                                                     belt-and-braces)
#   ~/graphwise-stack-aws/charts/graphwise-stack/values.yaml
#                                                    (your edited copy with
#                                                     Bedrock creds + n8n
#                                                     license)
#
# Files that DON'T need backing up (regenerable):
#   /tmp/values-<sub>.yaml         -- regenerated by render-values.sh
#   ~/.kube/config                 -- regenerated by KIND
#   ~/NEXT_STEPS.txt               -- regenerated by cloud-init
#
# Usage:
#   ./scripts/laptop/pull-from-ec2.sh \
#       --key ~/.ssh/graphwise-stack.pem --host 54.149.12.34
#
# Pass `--dest <dir>` to override the default backup location.
#
# Environment variable defaults:
#   GRAPHWISE_KEY    same as --key  (e.g. ~/.ssh/graphwise-stack.pem)
#   GRAPHWISE_HOST   same as --host (e.g. 54.149.12.34 or
#                    stroker.semantic-proof.com)
#   GRAPHWISE_USER   same as --user (default: ec2-user)
# Set these once in your shell rc and you can drop --key/--host
# from every invocation. CLI flags override env vars.

set -euo pipefail

KEY="${GRAPHWISE_KEY:-}"
HOST="${GRAPHWISE_HOST:-}"
USER_NAME="${GRAPHWISE_USER:-ec2-user}"
DEST=""

usage() {
    cat <<EOF
Usage: $0 [--key <key.pem>] [--host <ec2-host>] [options]

Required (CLI flag OR environment variable):
  --key <path.pem>     SSH private key
                       env: GRAPHWISE_KEY
  --host <eip-or-fqdn> EC2 host (Elastic IP or DNS)
                       env: GRAPHWISE_HOST

Optional:
  --user <name>        SSH user (default: ec2-user)
                       env: GRAPHWISE_USER
  --dest <dir>         Backup destination directory (default:
                       ~/graphwise-backup-<host>-<UTC-timestamp>)

Tip: export GRAPHWISE_KEY and GRAPHWISE_HOST in your shell rc so you
can run this without --key/--host every time. Example:

  export GRAPHWISE_KEY=~/.ssh/graphwise-stack.pem
  export GRAPHWISE_HOST=stroker.semantic-proof.com
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --key)  KEY="$2"; shift 2 ;;
        --host) HOST="$2"; shift 2 ;;
        --user) USER_NAME="$2"; shift 2 ;;
        --dest) DEST="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "ERROR: unknown flag '$1'" >&2; usage; exit 1 ;;
    esac
done

if [[ -z "$KEY" || -z "$HOST" ]]; then
    echo "ERROR: --key and --host are required (or set GRAPHWISE_KEY / GRAPHWISE_HOST)." >&2
    usage
    exit 1
fi

if [[ ! -f "$KEY" ]]; then
    echo "ERROR: SSH key not found: $KEY" >&2
    exit 1
fi

if [[ -z "$DEST" ]]; then
    DEST="$HOME/graphwise-backup-${HOST}-$(date -u +%Y%m%d-%H%M%S)"
fi
mkdir -p "$DEST"

# Manifest: each entry is "label|remote-relative-path|tar-relative-path".
# Remote paths are relative to the SSH user's $HOME on the EC2.
# Tar paths are relative to the staging dir, mirroring the layout this
# script has always produced under $DEST.
FILES=(
    "files/licenses/poolparty.key|graphwise-stack-aws/files/licenses/poolparty.key|licenses/poolparty.key"
    "files/licenses/graphdb.license|graphwise-stack-aws/files/licenses/graphdb.license|licenses/graphdb.license"
    "files/licenses/uv-license.key|graphwise-stack-aws/files/licenses/uv-license.key|licenses/uv-license.key"
    ".ontotext/maven-user|.ontotext/maven-user|ontotext/maven-user"
    ".ontotext/maven-pass|.ontotext/maven-pass|ontotext/maven-pass"
    "graphwise-secrets.yaml|graphwise-secrets.yaml|values/graphwise-secrets.yaml"
    "values.yaml (edited)|graphwise-stack-aws/charts/graphwise-stack/values.yaml|values/graphwise-stack-values.yaml"
    "dashboard-kubeconfig.yaml|dashboard-kubeconfig.yaml|dashboard-kubeconfig.yaml"
)

echo "Backing up to: $DEST"
echo
echo "Building backup archive on $HOST (one ssh, one scp)..."

# Build the remote shell snippet. For each manifest entry we either
# stage the file under a unique temp dir and print "OK:<label>", or
# print "MISSING:<label>". After staging we tar+gzip the whole tree.
REMOTE_SCRIPT='set -euo pipefail
STAGE=$(mktemp -d /tmp/graphwise-pull.XXXXXX)
trap '\''rm -rf "$STAGE"'\'' EXIT
'
for entry in "${FILES[@]}"; do
    IFS='|' read -r label remote rel <<<"$entry"
    # shell-escape for the remote heredoc -- the values are
    # repo-controlled (no untrusted input) but quoting is still safer.
    REMOTE_SCRIPT+="
LABEL=$(printf '%q' "$label")
REMOTE=$(printf '%q' "$remote")
REL=$(printf '%q' "$rel")
if [ -f \"\$HOME/\$REMOTE\" ]; then
    mkdir -p \"\$STAGE/\$(dirname \"\$REL\")\"
    cp -p \"\$HOME/\$REMOTE\" \"\$STAGE/\$REL\"
    echo \"OK:\$LABEL\" >&2
else
    echo \"MISSING:\$LABEL\" >&2
fi
"
done
REMOTE_SCRIPT+='
# Emit the tarball to stdout. Stderr already carries OK/MISSING lines.
( cd "$STAGE" && tar -czf - . )
'

# Run the snippet over SSH. Stdout = tar bytes -> local file.
# Stderr = OK/MISSING inventory -> we capture and replay locally.
TARBALL="$DEST/.graphwise-backup.tar.gz"
INVENTORY=$(mktemp -t graphwise-pull-inv.XXXXXX)
trap 'rm -f "$INVENTORY" "$TARBALL"' EXIT

if ! ssh -i "$KEY" -o StrictHostKeyChecking=accept-new \
        "$USER_NAME@$HOST" "bash -s" \
        > "$TARBALL" \
        2> "$INVENTORY" \
        <<<"$REMOTE_SCRIPT"; then
    echo "ERROR: remote tar pipeline failed. Inventory so far:" >&2
    cat "$INVENTORY" >&2
    exit 1
fi

# Replay the per-file inventory with the original formatting.
echo
while IFS= read -r line; do
    case "$line" in
        OK:*)      printf '  %-30s ok\n'                       "${line#OK:}" ;;
        MISSING:*) printf '  %-30s missing on host -- skipped\n' "${line#MISSING:}" ;;
        *)         printf '  %s\n' "$line" ;;
    esac
done < "$INVENTORY"

# Extract the tarball into $DEST. Tar will create licenses/, ontotext/,
# values/ subdirs as encoded by the rel paths in the manifest.
if ! tar -xzf "$TARBALL" -C "$DEST"; then
    echo "ERROR: failed to extract tarball into $DEST" >&2
    exit 1
fi
rm -f "$TARBALL"

# Drop macOS Finder droppings that sneak into the backup dir.
find "$DEST" -name '.DS_Store' -delete 2>/dev/null || true

# Lock down perms so back-up files don't widen permissions.
chmod -R go-rwx "$DEST"

echo
echo "Backup tree:"
find "$DEST" -type f | sort
echo
echo "Done. Total size: $(du -sh "$DEST" | cut -f1)"
