#!/usr/bin/env bash
# pull-from-ec2.sh -- run from your LAPTOP. Downloads license files,
# Maven creds, and per-deployment state from a deployed EC2 host
# into a timestamped backup directory before `terraform destroy`.
#
# What gets pulled:
#   ~/graphwise-stack-aws/files/licenses/*           (vendor blobs)
#   ~/.ontotext/maven-user                           (Graphwise Maven login)
#   ~/.ontotext/maven-pass                           (Graphwise Maven password)
#   ~/graphwise-secrets.yaml                         (Terraform-generated n8n
#                                                     encryption key overlay --
#                                                     also recoverable from
#                                                     terraform state, but
#                                                     belt-and-braces)
#   ~/graphwise-stack-aws/charts/graphwise-stack/values.yaml
#                                                    (your edited copy with
#                                                     Bedrock creds + n8n
#                                                     license)
#
# Files that DON'T need backing up (regenerable):
#   /tmp/values-<sub>.yaml         -- regenerated by render-values.sh
#   ~/.kube/config                 -- regenerated by KIND
#   ~/NEXT_STEPS.txt               -- regenerated by cloud-init
#
# Usage:
#   ./scripts/laptop/pull-from-ec2.sh \
#       --key ~/.ssh/graphwise-stack.pem --host 54.149.12.34
#
# Pass `--dest <dir>` to override the default backup location.
#
# Environment variable defaults:
#   GRAPHWISE_KEY    same as --key  (e.g. ~/.ssh/graphwise-stack.pem)
#   GRAPHWISE_HOST   same as --host (e.g. 54.149.12.34 or
#                    stroker.semantic-proof.com)
#   GRAPHWISE_USER   same as --user (default: ec2-user)
# Set these once in your shell rc and you can drop --key/--host
# from every invocation. CLI flags override env vars.

set -euo pipefail

KEY="${GRAPHWISE_KEY:-}"
HOST="${GRAPHWISE_HOST:-}"
USER_NAME="${GRAPHWISE_USER:-ec2-user}"
DEST=""

usage() {
    cat <<EOF
Usage: $0 [--key <key.pem>] [--host <ec2-host>] [options]

Required (CLI flag OR environment variable):
  --key <path.pem>     SSH private key
                       env: GRAPHWISE_KEY
  --host <eip-or-fqdn> EC2 host (Elastic IP or DNS)
                       env: GRAPHWISE_HOST

Optional:
  --user <name>        SSH user (default: ec2-user)
                       env: GRAPHWISE_USER
  --dest <dir>         Backup destination directory (default:
                       ~/graphwise-backup-<host>-<UTC-timestamp>)

Tip: export GRAPHWISE_KEY and GRAPHWISE_HOST in your shell rc so you
can run this without --key/--host every time. Example:

  export GRAPHWISE_KEY=~/.ssh/graphwise-stack.pem
  export GRAPHWISE_HOST=stroker.semantic-proof.com
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --key)  KEY="$2"; shift 2 ;;
        --host) HOST="$2"; shift 2 ;;
        --user) USER_NAME="$2"; shift 2 ;;
        --dest) DEST="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "ERROR: unknown flag '$1'" >&2; usage; exit 1 ;;
    esac
done

if [[ -z "$KEY" || -z "$HOST" ]]; then
    echo "ERROR: --key and --host are required (or set GRAPHWISE_KEY / GRAPHWISE_HOST)." >&2
    usage
    exit 1
fi

if [[ ! -f "$KEY" ]]; then
    echo "ERROR: SSH key not found: $KEY" >&2
    exit 1
fi

if [[ -z "$DEST" ]]; then
    DEST="$HOME/graphwise-backup-${HOST}-$(date -u +%Y%m%d-%H%M%S)"
fi
mkdir -p "$DEST/licenses" "$DEST/ontotext" "$DEST/values"

# scp_from prints "(missing)" instead of failing when the remote
# file isn't there -- some users may not have all of these.
scp_from() {
    local label="$1" src="$2" dst="$3"
    if scp -i "$KEY" -o StrictHostKeyChecking=accept-new "$USER_NAME@$HOST:$src" "$dst" >/dev/null 2>&1; then
        printf '  %-30s ok -> %s\n' "$label" "$dst"
    else
        printf '  %-30s missing on host -- skipped\n' "$label"
        rm -f "$dst"
    fi
}

echo "Backing up to: $DEST"
echo

echo "Licenses:"
scp_from "files/licenses/poolparty.key"   "graphwise-stack-aws/files/licenses/poolparty.key"   "$DEST/licenses/poolparty.key"
scp_from "files/licenses/graphdb.license" "graphwise-stack-aws/files/licenses/graphdb.license" "$DEST/licenses/graphdb.license"
scp_from "files/licenses/uv-license.key"  "graphwise-stack-aws/files/licenses/uv-license.key"  "$DEST/licenses/uv-license.key"

echo "Maven creds:"
scp_from ".ontotext/maven-user"           ".ontotext/maven-user"                                "$DEST/ontotext/maven-user"
scp_from ".ontotext/maven-pass"           ".ontotext/maven-pass"                                "$DEST/ontotext/maven-pass"

echo "Helm values + secrets overlay:"
scp_from "graphwise-secrets.yaml"         "graphwise-secrets.yaml"                              "$DEST/values/graphwise-secrets.yaml"
scp_from "values.yaml (edited)"           "graphwise-stack-aws/charts/graphwise-stack/values.yaml" "$DEST/values/graphwise-stack-values.yaml"

echo "Kubernetes Dashboard kubeconfig:"
scp_from "dashboard-kubeconfig.yaml"      "dashboard-kubeconfig.yaml"                           "$DEST/dashboard-kubeconfig.yaml"

# Drop macOS Finder droppings that sneak into the backup dir.
find "$DEST" -name '.DS_Store' -delete 2>/dev/null || true

# Lock down perms so back-up files don't widen permissions.
chmod -R go-rwx "$DEST"

echo
echo "Backup tree:"
find "$DEST" -type f | sort
echo
echo "Done. Total size: $(du -sh "$DEST" | cut -f1)"
