#!/usr/bin/env bash
# push-secrets.sh -- copy your locally-saved graphwise-secrets.yaml to
# the EC2 host as ~/graphwise-secrets.yaml. Reuse pattern: keep one
# canonical copy on your laptop (gitignored), scp it back after every
# `terraform destroy && terraform apply` cycle. That preserves all
# operator-supplied secrets across rebuilds without re-typing.
#
# What's in the file (single source of truth):
#   - maven.user / maven.pass      (Graphwise private registry)
#   - graphrag-secrets.awsCredentials.{region, accessKeyId, secretAccessKey}
#   - graphrag-secrets.n8nLicense.activationKey
#   - graphrag-secrets.n8nEncryption.key   (auto-generated by Terraform;
#                                           DO NOT carry this from a
#                                           previous deployment -- a
#                                           fresh terraform apply
#                                           generates a fresh value
#                                           which IS what the new n8n
#                                           DB needs)
#
# Important n8nEncryption note: the new EC2's cloud-init wrote a
# fresh n8nEncryption.key into ~/graphwise-secrets.yaml. This script
# preserves that key by default (merging it into your local copy
# before push). Override with --keep-local-encryption-key only if you
# know you're restoring against the same n8n DB the old key encrypted.
#
# Required env (or pass via flags):
#   GRAPHWISE_KEY    path to .pem
#   GRAPHWISE_HOST   subdomain or EIP
#   GRAPHWISE_USER   ec2-user (default)
#
# Usage:
#   ./scripts/laptop/push-secrets.sh                       (uses ~/graphwise-secrets.yaml)
#   ./scripts/laptop/push-secrets.sh ~/path/to/secrets.yaml
#   ./scripts/laptop/push-secrets.sh --keep-local-encryption-key
#
# Exit codes:
#   0 -- file pushed successfully
#   1 -- ssh / scp / merge failure
#   2 -- usage / missing local file / missing env

set -euo pipefail

if [ -t 1 ]; then
    GREEN=$'\033[32m'; RED=$'\033[31m'; YELLOW=$'\033[33m'
    BOLD=$'\033[1m'; DIM=$'\033[2m'; RESET=$'\033[0m'
else
    GREEN=""; RED=""; YELLOW=""; BOLD=""; DIM=""; RESET=""
fi

KEEP_LOCAL_ENCRYPTION_KEY=no
LOCAL_FILE="$HOME/graphwise-secrets.yaml"
while [ $# -gt 0 ]; do
    case "$1" in
        --keep-local-encryption-key) KEEP_LOCAL_ENCRYPTION_KEY=yes; shift ;;
        -h|--help)
            sed -n '2,/^$/p' "$0" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        -*) echo "${RED}Unknown flag: $1${RESET}" >&2; exit 2 ;;
        *) LOCAL_FILE="$1"; shift ;;
    esac
done

KEY="${GRAPHWISE_KEY:-}"
HOST="${GRAPHWISE_HOST:-}"
USR="${GRAPHWISE_USER:-ec2-user}"

if [ -z "$KEY" ] || [ -z "$HOST" ]; then
    cat >&2 <<USAGE
${RED}ERROR:${RESET} GRAPHWISE_KEY and GRAPHWISE_HOST must be set in the environment.
Set them once (per SETUP §7):
    export GRAPHWISE_KEY=~/.ssh/graphwise-stack.pem
    export GRAPHWISE_HOST=stroker.semantic-demo.com
    export GRAPHWISE_USER=ec2-user
USAGE
    exit 2
fi

if [ ! -f "$LOCAL_FILE" ]; then
    cat >&2 <<USAGE
${RED}ERROR:${RESET} local file not found: $LOCAL_FILE

Create one by either:
  (a) Pulling the EC2 copy down first time you push this:
      scp -i \$GRAPHWISE_KEY \$GRAPHWISE_USER@\$GRAPHWISE_HOST:~/graphwise-secrets.yaml ~/
  (b) Copy charts/graphwise-stack/values.yaml's graphrag-secrets block
      into a new file at \$HOME/graphwise-secrets.yaml and add a
      maven: block at the top -- see infra/terraform/user-data.sh.tpl
      for the full template.
USAGE
    exit 2
fi

echo "Local file:  ${BOLD}$LOCAL_FILE${RESET}"
echo "Remote host: ${BOLD}$USR@$HOST${RESET}:~/graphwise-secrets.yaml"
echo

# n8nEncryption.key handling. Default: read the remote (fresh) key and
# splice it into the local file before push, so the new n8n DB is
# encryptable with the key it was given on first boot. The local
# file's old key would be from the PREVIOUS deployment whose DB no
# longer exists.
if [ "$KEEP_LOCAL_ENCRYPTION_KEY" = "no" ]; then
    echo "Reading fresh n8nEncryption.key from remote..."
    REMOTE_KEY=$(ssh -i "$KEY" "$USR@$HOST" 'python3 -c "
import yaml
with open(\"/home/ec2-user/graphwise-secrets.yaml\") as f:
    d = yaml.safe_load(f) or {}
print(((d.get(\"graphrag-secrets\") or {}).get(\"n8nEncryption\") or {}).get(\"key\") or \"\")
"' 2>/dev/null)
    if [ -z "$REMOTE_KEY" ]; then
        echo "${RED}ERROR:${RESET} couldn't read n8nEncryption.key from remote ~/graphwise-secrets.yaml" >&2
        echo "Is the EC2 cloud-init complete? Verify with:" >&2
        echo "  ssh -i \$GRAPHWISE_KEY \$GRAPHWISE_USER@\$GRAPHWISE_HOST 'cat ~/graphwise-secrets.yaml'" >&2
        exit 1
    fi
    printf '%s✓ remote n8nEncryption.key (first 8): %s...%s\n' "$GREEN" "${REMOTE_KEY:0:8}" "$RESET"

    # Splice into a temp copy of the local file so we don't mutate the
    # operator's source-of-truth. python3 + PyYAML preserves structure.
    TMP_FILE=$(mktemp -t graphwise-secrets.XXXXXX.yaml)
    trap 'rm -f "$TMP_FILE"' EXIT
    REMOTE_KEY="$REMOTE_KEY" python3 -c "
import os, yaml, sys
with open('$LOCAL_FILE') as f:
    d = yaml.safe_load(f) or {}
gs = d.setdefault('graphrag-secrets', {})
gs.setdefault('n8nEncryption', {})['key'] = os.environ['REMOTE_KEY']
with open('$TMP_FILE', 'w') as f:
    yaml.safe_dump(d, f, default_flow_style=False, sort_keys=False)
"
    PUSH_FILE="$TMP_FILE"
    echo "${DIM}Spliced fresh remote key into a temp copy; your local file is unchanged.${RESET}"
else
    echo "${YELLOW}--keep-local-encryption-key:${RESET} pushing local file as-is."
    PUSH_FILE="$LOCAL_FILE"
fi

echo
echo "Pushing..."
scp -i "$KEY" "$PUSH_FILE" "$USR@$HOST:~/graphwise-secrets.yaml"

echo
printf '%s✓ pushed.%s Verify with:\n' "$GREEN$BOLD" "$RESET"
echo "  ssh -i \$GRAPHWISE_KEY \$GRAPHWISE_USER@\$GRAPHWISE_HOST 'ls -la ~/graphwise-secrets.yaml && head -20 ~/graphwise-secrets.yaml'"
echo
echo "Then re-run scripts/reset-helm.sh on the EC2 to pick up the values."
